class PrimaryRoute {
  static const String initialRoute = '/';
  static const String onBoard = '/onboarding';
  static const String onBoard3 = '/onboarding3';
  static const String login = '/login';
  static const String register = '/register';
  static const String verification = '/verification';
  static const String otpScreen = '/otpscreen';
  static const String forgotPassword = '/forgot';
  static const String resetPassword = '/resetpassword';
  static const String home = '/home';
  static const String history = '/history';
  static const String notification = '/notification';
  static const String securitySetting = '/securitysetting';
  static const String biometric = '/biometric';
  static const String deleteAccount = '/deleteAccount';
  static const String help_support = '/helpsupport';
  static const String editProfile = '/editprofile';
  static const String photo_creation = '/photocreation';
  static const String photo_preview = '/photopreview';
  static const String selectedPhoto = '/selectedphoto';
  static const String assistant = '/assistant';
  static const String popularCountires = '/popularcountries';
  static const String payment_method= '/paymentmethod';
  static const String report_bug= '/reportbug';
  static const String ticket_management= '/ticketmanagement';
  static const String chat_screen= '/chatscreen';
  static const String drag= '/drag';
}