import 'package:snapid/utlis/country_model.dart';
List<Country> allCountries = [
  Country(name: "Andorra", code: "AD", flag: "assets/flags/ad.svg", currencySign: "EUR", dialCode: "+376"),
  Country(name: "United Arab Emirates", code: "AE", flag: "assets/flags/ae.svg", currencySign: "AED", dialCode: "+971"),
  Country(name: "Afghanistan", code: "AF", flag: "assets/flags/af.svg", currencySign: "AFN", dialCode: "+93"),
  Country(name: "Antigua and Barbuda", code: "AG", flag: "assets/flags/ag.svg", currencySign: "XCD", dialCode: "+1-268"),
  Country(name: "Anguilla", code: "AI", flag: "assets/flags/ai.svg", currencySign: "XCD", dialCode: "+1-264"),
  Country(name: "Albania", code: "AL", flag: "assets/flags/al.svg", currencySign: "ALL", dialCode: "+355"),
  Country(name: "Armenia", code: "AM", flag: "assets/flags/am.svg", currencySign: "AMD", dialCode: "+374"),
  Country(name: "Angola", code: "AO", flag: "assets/flags/ao.svg", currencySign: "AOA", dialCode: "+244"),
  Country(name: "Antarctica", code: "AQ", flag: "assets/flags/aq.svg", currencySign: "XCD", dialCode: "+672"),
  Country(name: "Argentina", code: "AR", flag: "assets/flags/ar.svg", currencySign: "ARS", dialCode: "+54"),
  Country(name: "American Samoa", code: "AS", flag: "assets/flags/as.svg", currencySign: "USD", dialCode: "+1-684"),
  Country(name: "Austria", code: "AT", flag: "assets/flags/at.svg", currencySign: "EUR", dialCode: "+43"),
  Country(name: "Australia", code: "AU", flag: "assets/flags/au.svg", currencySign: "AUD", dialCode: "+61"),
  Country(name: "Aruba", code: "AW", flag: "assets/flags/aw.svg", currencySign: "AWG", dialCode: "+297"),
  Country(name: "Azerbaijan", code: "AZ", flag: "assets/flags/az.svg", currencySign: "AZN", dialCode: "+994"),
  Country(name: "Bosnia and Herzegovina", code: "BA", flag: "assets/flags/ba.svg", currencySign: "BAM", dialCode: "+387"),
  Country(name: "Barbados", code: "BB", flag: "assets/flags/bb.svg", currencySign: "BBD", dialCode: "+1-246"),
  Country(name: "Bangladesh", code: "BD", flag: "assets/flags/bd.svg", currencySign: "BDT", dialCode: "+880"),
  Country(name: "Belgium", code: "BE", flag: "assets/flags/be.svg", currencySign: "EUR", dialCode: "+32"),
  Country(name: "Burkina Faso", code: "BF", flag: "assets/flags/bf.svg", currencySign: "XOF", dialCode: "+226"),
  Country(name: "Bulgaria", code: "BG", flag: "assets/flags/bg.svg", currencySign: "BGN", dialCode: "+359"),
  Country(name: "Bahrain", code: "BH", flag: "assets/flags/bh.svg", currencySign: "BHD", dialCode: "+973"),
  Country(name: "Burundi", code: "BI", flag: "assets/flags/bi.svg", currencySign: "BIF", dialCode: "+257"),
  Country(name: "Benin", code: "BJ", flag: "assets/flags/bj.svg", currencySign: "XOF", dialCode: "+229"),
  Country(name: "Saint Barthélemy", code: "BL", flag: "assets/flags/bl.svg", currencySign: "", dialCode: "+590"),
  Country(name: "Bermuda", code: "BM", flag: "assets/flags/bm.svg", currencySign: "BMD", dialCode: "+1-441"),
  Country(name: "Bolivia, Plurinational State of", code: "BO", flag: "assets/flags/bo.svg", currencySign: "BOB", dialCode: "+591"),
  Country(name: "Caribbean Netherlands", code: "BQ", flag: "assets/flags/bq.svg", currencySign: "", dialCode: "+599"),
  Country(name: "Bahamas", code: "BS", flag: "assets/flags/bs.svg", currencySign: "BSD", dialCode: "+1-242"),
  Country(name: "Bhutan", code: "BT", flag: "assets/flags/bt.svg", currencySign: "BTN", dialCode: "+975"),
  Country(name: "Bouvet Island", code: "BV", flag: "assets/flags/bv.svg", currencySign: "NOK", dialCode: "+47"),
  Country(name: "Botswana", code: "BW", flag: "assets/flags/bw.svg", currencySign: "BWP", dialCode: "+267"),
  Country(name: "Belize", code: "BZ", flag: "assets/flags/bz.svg", currencySign: "BZD", dialCode: "+501"),
  Country(name: "Canada", code: "CA", flag: "assets/flags/ca.svg", currencySign: "CAD", dialCode: "+1"),
  Country(name: "Cocos (Keeling) Islands", code: "CC", flag: "assets/flags/cc.svg", currencySign: "AUD", dialCode: "+61"),
  Country(name: "Congo, the Democratic Republic of the", code: "CD", flag: "assets/flags/cd.svg", currencySign: "CDF", dialCode: "+243"),
  Country(name: "Central African Republic", code: "CF", flag: "assets/flags/cf.svg", currencySign: "XAF", dialCode: "+236"),
  Country(name: "Republic of the Congo", code: "CG", flag: "assets/flags/cg.svg", currencySign: "XAF", dialCode: "+242"),
  Country(name: "Switzerland", code: "CH", flag: "assets/flags/ch.svg", currencySign: "CHF", dialCode: "+41"),
  Country(name: "Cook Islands", code: "CK", flag: "assets/flags/ck.svg", currencySign: "NZD", dialCode: "+682"),
  Country(name: "Chile", code: "CL", flag: "assets/flags/cl.svg", currencySign: "CLP", dialCode: "+56"),
  Country(name: "Cameroon", code: "CM", flag: "assets/flags/cm.svg", currencySign: "XAF", dialCode: "+237"),
  Country(name: "China (People's Republic of China)", code: "CN", flag: "assets/flags/cn.svg", currencySign: "CNY", dialCode: "+86"),
  Country(name: "Colombia", code: "CO", flag: "assets/flags/co.svg", currencySign: "COP", dialCode: "+57"),
  Country(name: "Costa Rica", code: "CR", flag: "assets/flags/cr.svg", currencySign: "CRC", dialCode: "+506"),
  Country(name: "Cuba", code: "CU", flag: "assets/flags/cu.svg", currencySign: "CUP", dialCode: "+53"),
  Country(name: "Cape Verde", code: "CV", flag: "assets/flags/cv.svg", currencySign: "CVE", dialCode: "+238"),
  Country(name: "Christmas Island", code: "CX", flag: "assets/flags/cx.svg", currencySign: "AUD", dialCode: "+61"),
  Country(name: "Cyprus", code: "CY", flag: "assets/flags/cy.svg", currencySign: "EUR", dialCode: "+357"),
  Country(name: "Czech Republic", code: "CZ", flag: "assets/flags/cz.svg", currencySign: "CZK", dialCode: "+420"),
  Country(name: "Germany", code: "DE", flag: "assets/flags/de.svg", currencySign: "EUR", dialCode: "+49"),
  Country(name: "Djibouti", code: "DJ", flag: "assets/flags/dj.svg", currencySign: "DJF", dialCode: "+253"),
  Country(name: "Denmark", code: "DK", flag: "assets/flags/dk.svg", currencySign: "DKK", dialCode: "+45"),
  Country(name: "Dominica", code: "DM", flag: "assets/flags/dm.svg", currencySign: "XCD", dialCode: "+1-767"),
  Country(name: "Dominican Republic", code: "DO", flag: "assets/flags/do.svg", currencySign: "DOP", dialCode: "+1-809"),
  Country(name: "Algeria", code: "DZ", flag: "assets/flags/dz.svg", currencySign: "DZD", dialCode: "+213"),
  Country(name: "Ecuador", code: "EC", flag: "assets/flags/ec.svg", currencySign: "ECS", dialCode: "+593"),
  Country(name: "Estonia", code: "EE", flag: "assets/flags/ee.svg", currencySign: "EUR", dialCode: "+372"),
  Country(name: "Egypt", code: "EG", flag: "assets/flags/eg.svg", currencySign: "EGP", dialCode: "+20"),
  Country(name: "Western Sahara", code: "EH", flag: "assets/flags/eh.svg", currencySign: "MAD", dialCode: "+212"),
  Country(name: "Eritrea", code: "ER", flag: "assets/flags/er.svg", currencySign: "ERN", dialCode: "+291"),
  Country(name: "Spain", code: "ES", flag: "assets/flags/es.svg", currencySign: "EUR", dialCode: "+34"),
  Country(name: "Ethiopia", code: "ET", flag: "assets/flags/et.svg", currencySign: "ETB", dialCode: "+251"),
  Country(name: "Europe", code: "EU", flag: "assets/flags/eu.svg", currencySign: "", dialCode: ""),
  Country(name: "Finland", code: "FI", flag: "assets/flags/fi.svg", currencySign: "EUR", dialCode: "+358"),
  Country(name: "Fiji", code: "FJ", flag: "assets/flags/fj.svg", currencySign: "FJD", dialCode: "+679"),
  Country(name: "Falkland Islands (Malvinas)", code: "FK", flag: "assets/flags/fk.svg", currencySign: "FKP", dialCode: "+500"),
  Country(name: "Micronesia, Federated States of", code: "FM", flag: "assets/flags/fm.svg", currencySign: "USD", dialCode: "+691"),
  Country(name: "Faroe Islands", code: "FO", flag: "assets/flags/fo.svg", currencySign: "DKK", dialCode: "+298"),
  Country(name: "France", code: "FR", flag: "assets/flags/fr.svg", currencySign: "EUR", dialCode: "+33"),
  Country(name: "Gabon", code: "GA", flag: "assets/flags/ga.svg", currencySign: "XAF", dialCode: "+241"),
  Country(name: "England", code: "GB-ENG", flag: "assets/flags/gb-eng.svg", currencySign: "GBP", dialCode: "+44"),
  Country(name: "Northern Ireland", code: "GB-NIR", flag: "assets/flags/gb-nir.svg", currencySign: "GBP", dialCode: "+44"),
  Country(name: "Scotland", code: "GB-SCT", flag: "assets/flags/gb-sct.svg", currencySign: "GBP", dialCode: "+44"),
  Country(name: "Wales", code: "GB-WLS", flag: "assets/flags/gb-wls.svg", currencySign: "GBP", dialCode: "+44"),
  Country(name: "United Kingdom", code: "GB", flag: "assets/flags/gb.svg", currencySign: "GBP", dialCode: "+44"),
  Country(name: "Grenada", code: "GD", flag: "assets/flags/gd.svg", currencySign: "XCD", dialCode: "+1-473"),
  Country(name: "Georgia", code: "GE", flag: "assets/flags/ge.svg", currencySign: "GEL", dialCode: "+995"),
  Country(name: "French Guiana", code: "GF", flag: "assets/flags/gf.svg", currencySign: "EUR", dialCode: "+594"),
  Country(name: "Guernsey", code: "GG", flag: "assets/flags/gg.svg", currencySign: "", dialCode: "+44"),
  Country(name: "Ghana", code: "GH", flag: "assets/flags/gh.svg", currencySign: "GHS", dialCode: "+233"),
  Country(name: "Gibraltar", code: "GI", flag: "assets/flags/gi.svg", currencySign: "GIP", dialCode: "+350"),
  Country(name: "Greenland", code: "GL", flag: "assets/flags/gl.svg", currencySign: "DKK", dialCode: "+299"),
  Country(name: "Gambia", code: "GM", flag: "assets/flags/gm.svg", currencySign: "GMD", dialCode: "+220"),
  Country(name: "Guinea", code: "GN", flag: "assets/flags/gn.svg", currencySign: "GNF", dialCode: "+224"),
  Country(name: "Guadeloupe", code: "GP", flag: "assets/flags/gp.svg", currencySign: "EUR", dialCode: "+590"),
  Country(name: "Equatorial Guinea", code: "GQ", flag: "assets/flags/gq.svg", currencySign: "XAF", dialCode: "+240"),
  Country(name: "Greece", code: "GR", flag: "assets/flags/gr.svg", currencySign: "EUR", dialCode: "+30"),
  Country(name: "South Georgia and the South Sandwich Islands", code: "GS", flag: "assets/flags/gs.svg", currencySign: "GBP", dialCode: "+500"),
  Country(name: "Guatemala", code: "GT", flag: "assets/flags/gt.svg", currencySign: "QTQ", dialCode: "+502"),
  Country(name: "Guam", code: "GU", flag: "assets/flags/gu.svg", currencySign: "USD", dialCode: "+1-671"),
  Country(name: "Guinea-Bissau", code: "GW", flag: "assets/flags/gw.svg", currencySign: "CFA", dialCode: "+245"),
  Country(name: "Guyana", code: "GY", flag: "assets/flags/gy.svg", currencySign: "GYD", dialCode: "+592"),
  Country(name: "Hong Kong", code: "HK", flag: "assets/flags/hk.svg", currencySign: "HKD", dialCode: "+852"),
  Country(name: "Heard Island and McDonald Islands", code: "HM", flag: "assets/flags/hm.svg", currencySign: "AUD", dialCode: "+672"),
  Country(name: "Honduras", code: "HN", flag: "assets/flags/hn.svg", currencySign: "HNL", dialCode: "+504"),
  Country(name: "Croatia", code: "HR", flag: "assets/flags/hr.svg", currencySign: "EUR", dialCode: "+385"),
  Country(name: "Haiti", code: "HT", flag: "assets/flags/ht.svg", currencySign: "HTG", dialCode: "+509"),
  Country(name: "Hungary", code: "HU", flag: "assets/flags/hu.svg", currencySign: "HUF", dialCode: "+36"),
  Country(name: "Indonesia", code: "ID", flag: "assets/flags/id.svg", currencySign: "IDR", dialCode: "+62"),
  Country(name: "Ireland", code: "IE", flag: "assets/flags/ie.svg", currencySign: "EUR", dialCode: "+353"),
  Country(name: "Israel", code: "IL", flag: "assets/flags/il.svg", currencySign: "ILS", dialCode: "+972"),
  Country(name: "Isle of Man", code: "IM", flag: "assets/flags/im.svg", currencySign: "", dialCode: "+44"),
  Country(name: "India", code: "IN", flag: "assets/flags/in.svg", currencySign: "INR", dialCode: "+91"),
  Country(name: "British Indian Ocean Territory", code: "IO", flag: "assets/flags/io.svg", currencySign: "USD", dialCode: "+246"),
  Country(name: "Iraq", code: "IQ", flag: "assets/flags/iq.svg", currencySign: "IQD", dialCode: "+964"),
  Country(name: "Iran, Islamic Republic of", code: "IR", flag: "assets/flags/ir.svg", currencySign: "IRR", dialCode: "+98"),
  Country(name: "Iceland", code: "IS", flag: "assets/flags/is.svg", currencySign: "ISK", dialCode: "+354"),
  Country(name: "Italy", code: "IT", flag: "assets/flags/it.svg", currencySign: "EUR", dialCode: "+39"),
  Country(name: "Jersey", code: "JE", flag: "assets/flags/je.svg", currencySign: "", dialCode: "+44"),
  Country(name: "Jamaica", code: "JM", flag: "assets/flags/jm.svg", currencySign: "JMD", dialCode: "+1-876"),
  Country(name: "Jordan", code: "JO", flag: "assets/flags/jo.svg", currencySign: "JOD", dialCode: "+962"),
  Country(name: "Japan", code: "JP", flag: "assets/flags/jp.svg", currencySign: "JPY", dialCode: "+81"),
  Country(name: "Kenya", code: "KE", flag: "assets/flags/ke.svg", currencySign: "KES", dialCode: "+254"),
  Country(name: "Kyrgyzstan", code: "KG", flag: "assets/flags/kg.svg", currencySign: "KGS", dialCode: "+996"),
  Country(name: "Cambodia", code: "KH", flag: "assets/flags/kh.svg", currencySign: "KHR", dialCode: "+855"),
  Country(name: "Kiribati", code: "KI", flag: "assets/flags/ki.svg", currencySign: "AUD", dialCode: "+686"),
  Country(name: "Comoros", code: "KM", flag: "assets/flags/km.svg", currencySign: "KMF", dialCode: "+269"),
  Country(name: "Saint Kitts and Nevis", code: "KN", flag: "assets/flags/kn.svg", currencySign: "XCD", dialCode: "+1-869"),
  Country(name: "Korea, Democratic People's Republic of", code: "KP", flag: "assets/flags/kp.svg", currencySign: "KPW", dialCode: "+850"),
  Country(name: "Korea, Republic of", code: "KR", flag: "assets/flags/kr.svg", currencySign: "KRW", dialCode: "+82"),
  Country(name: "Kuwait", code: "KW", flag: "assets/flags/kw.svg", currencySign: "KWD", dialCode: "+965"),
  Country(name: "Cayman Islands", code: "KY", flag: "assets/flags/ky.svg", currencySign: "KYD", dialCode: "+1-345"),
  Country(name: "Kazakhstan", code: "KZ", flag: "assets/flags/kz.svg", currencySign: "KZT", dialCode: "+7"),
  Country(name: "Laos (Lao People's Democratic Republic)", code: "LA", flag: "assets/flags/la.svg", currencySign: "LAK", dialCode: "+856"),
  Country(name: "Lebanon", code: "LB", flag: "assets/flags/lb.svg", currencySign: "LBP", dialCode: "+961"),
  Country(name: "Saint Lucia", code: "LC", flag: "assets/flags/lc.svg", currencySign: "XCD", dialCode: "+1-758"),
  Country(name: "Liechtenstein", code: "LI", flag: "assets/flags/li.svg", currencySign: "CHF", dialCode: "+423"),
  Country(name: "Sri Lanka", code: "LK", flag: "assets/flags/lk.svg", currencySign: "LKR", dialCode: "+94"),
  Country(name: "Liberia", code: "LR", flag: "assets/flags/lr.svg", currencySign: "LRD", dialCode: "+231"),
  Country(name: "Lesotho", code: "LS", flag: "assets/flags/ls.svg", currencySign: "LSL", dialCode: "+266"),
  Country(name: "Lithuania", code: "LT", flag: "assets/flags/lt.svg", currencySign: "EUR", dialCode: "+370"),
  Country(name: "Luxembourg", code: "LU", flag: "assets/flags/lu.svg", currencySign: "EUR", dialCode: "+352"),
  Country(name: "Latvia", code: "LV", flag: "assets/flags/lv.svg", currencySign: "EUR", dialCode: "+371"),
  Country(name: "Libya", code: "LY", flag: "assets/flags/ly.svg", currencySign: "LYD", dialCode: "+218"),
  Country(name: "Morocco", code: "MA", flag: "assets/flags/ma.svg", currencySign: "MAD", dialCode: "+212"),
  Country(name: "Monaco", code: "MC", flag: "assets/flags/mc.svg", currencySign: "EUR", dialCode: "+377"),
  Country(name: "Moldova, Republic of", code: "MD", flag: "assets/flags/md.svg", currencySign: "MDL", dialCode: "+373"),
  Country(name: "Montenegro", code: "ME", flag: "assets/flags/me.svg", currencySign: "", dialCode: "+382"),
  Country(name: "Saint Martin", code: "MF", flag: "assets/flags/mf.svg", currencySign: "", dialCode: "+590"),
  Country(name: "Madagascar", code: "MG", flag: "assets/flags/mg.svg", currencySign: "MGF", dialCode: "+261"),
  Country(name: "Marshall Islands", code: "MH", flag: "assets/flags/mh.svg", currencySign: "USD", dialCode: "+692"),
  Country(name: "North Macedonia", code: "MK", flag: "assets/flags/mk.svg", currencySign: "MKD", dialCode: "+389"),
  Country(name: "Mali", code: "ML", flag: "assets/flags/ml.svg", currencySign: "XOF", dialCode: "+223"),
  Country(name: "Myanmar", code: "MM", flag: "assets/flags/mm.svg", currencySign: "MMR", dialCode: "+95"),
  Country(name: "Mongolia", code: "MN", flag: "assets/flags/mn.svg", currencySign: "MNT", dialCode: "+976"),
  Country(name: "Macao", code: "MO", flag: "assets/flags/mo.svg", currencySign: "MOP", dialCode: "+853"),
  Country(name: "Northern Mariana Islands", code: "MP", flag: "assets/flags/mp.svg", currencySign: "USD", dialCode: "+1-670"),
  Country(name: "Martinique", code: "MQ", flag: "assets/flags/mq.svg", currencySign: "EUR", dialCode: "+596"),
  Country(name: "Mauritania", code: "MR", flag: "assets/flags/mr.svg", currencySign: "MRO", dialCode: "+222"),
  Country(name: "Montserrat", code: "MS", flag: "assets/flags/ms.svg", currencySign: "XCD", dialCode: "+1-664"),
  Country(name: "Malta", code: "MT", flag: "assets/flags/mt.svg", currencySign: "EUR", dialCode: "+356"),
  Country(name: "Mauritius", code: "MU", flag: "assets/flags/mu.svg", currencySign: "MUR", dialCode: "+230"),
  Country(name: "Maldives", code: "MV", flag: "assets/flags/mv.svg", currencySign: "MVR", dialCode: "+960"),
  Country(name: "Malawi", code: "MW", flag: "assets/flags/mw.svg", currencySign: "MWK", dialCode: "+265"),
  Country(name: "Mexico", code: "MX", flag: "assets/flags/mx.svg", currencySign: "MXN", dialCode: "+52"),
  Country(name: "Malaysia", code: "MY", flag: "assets/flags/my.svg", currencySign: "MYR", dialCode: "+60"),
  Country(name: "Mozambique", code: "MZ", flag: "assets/flags/mz.svg", currencySign: "MZN", dialCode: "+258"),
  Country(name: "Namibia", code: "NA", flag: "assets/flags/na.svg", currencySign: "NAD", dialCode: "+264"),
  Country(name: "New Caledonia", code: "NC", flag: "assets/flags/nc.svg", currencySign: "XPF", dialCode: "+687"),
  Country(name: "Niger", code: "NE", flag: "assets/flags/ne.svg", currencySign: "XOF", dialCode: "+227"),
  Country(name: "Norfolk Island", code: "NF", flag: "assets/flags/nf.svg", currencySign: "AUD", dialCode: "+672"),
  Country(name: "Nigeria", code: "NG", flag: "assets/flags/ng.svg", currencySign: "NGN", dialCode: "+234"),
  Country(name: "Nicaragua", code: "NI", flag: "assets/flags/ni.svg", currencySign: "NIO", dialCode: "+505"),
  Country(name: "Netherlands", code: "NL", flag: "assets/flags/nl.svg", currencySign: "EUR", dialCode: "+31"),
  Country(name: "Norway", code: "NO", flag: "assets/flags/no.svg", currencySign: "NOK", dialCode: "+47"),
  Country(name: "Nepal", code: "NP", flag: "assets/flags/np.svg", currencySign: "NPR", dialCode: "+977"),
  Country(name: "Nauru", code: "NR", flag: "assets/flags/nr.svg", currencySign: "AUD", dialCode: "+674"),
  Country(name: "Niue", code: "NU", flag: "assets/flags/nu.svg", currencySign: "NZD", dialCode: "+683"),
  Country(name: "New Zealand", code: "NZ", flag: "assets/flags/nz.svg", currencySign: "NZD", dialCode: "+64"),
  Country(name: "Oman", code: "OM", flag: "assets/flags/om.svg", currencySign: "OMR", dialCode: "+968"),
  Country(name: "Panama", code: "PA", flag: "assets/flags/pa.svg", currencySign: "PAB", dialCode: "+507"),
  Country(name: "Peru", code: "PE", flag: "assets/flags/pe.svg", currencySign: "PEN", dialCode: "+51"),
  Country(name: "French Polynesia", code: "PF", flag: "assets/flags/pf.svg", currencySign: "XPF", dialCode: "+689"),
  Country(name: "Papua New Guinea", code: "PG", flag: "assets/flags/pg.svg", currencySign: "PGK", dialCode: "+675"),
  Country(name: "Philippines", code: "PH", flag: "assets/flags/ph.svg", currencySign: "PHP", dialCode: "+63"),
  Country(name: "Pakistan", code: "PK", flag: "assets/flags/pk.svg", currencySign: "PKR", dialCode: "+92"),
  Country(name: "Poland", code: "PL", flag: "assets/flags/pl.svg", currencySign: "PLN", dialCode: "+48"),
  Country(name: "Saint Pierre and Miquelon", code: "PM", flag: "assets/flags/pm.svg", currencySign: "EUR", dialCode: "+508"),
  Country(name: "Pitcairn", code: "PN", flag: "assets/flags/pn.svg", currencySign: "NZD", dialCode: "+64"),
  Country(name: "Puerto Rico", code: "PR", flag: "assets/flags/pr.svg", currencySign: "USD", dialCode: "+1-787"),
  Country(name: "Palestine", code: "PS", flag: "assets/flags/ps.svg", currencySign: "", dialCode: "+970"),
  Country(name: "Portugal", code: "PT", flag: "assets/flags/pt.svg", currencySign: "EUR", dialCode: "+351"),
  Country(name: "Palau", code: "PW", flag: "assets/flags/pw.svg", currencySign: "USD", dialCode: "+680"),
  Country(name: "Paraguay", code: "PY", flag: "assets/flags/py.svg", currencySign: "PYG", dialCode: "+595"),
  Country(name: "Qatar", code: "QA", flag: "assets/flags/qa.svg", currencySign: "QAR", dialCode: "+974"),
  Country(name: "Réunion", code: "RE", flag: "assets/flags/re.svg", currencySign: "EUR", dialCode: "+262"),
  Country(name: "Romania", code: "RO", flag: "assets/flags/ro.svg", currencySign: "RON", dialCode: "+40"),
  Country(name: "Serbia", code: "RS", flag: "assets/flags/rs.svg", currencySign: "RSD", dialCode: "+381"),
  Country(name: "Russian Federation", code: "RU", flag: "assets/flags/ru.svg", currencySign: "RUB", dialCode: "+7"),
  Country(name: "Rwanda", code: "RW", flag: "assets/flags/rw.svg", currencySign: "RWF", dialCode: "+250"),
  Country(name: "Saudi Arabia", code: "SA", flag: "assets/flags/sa.svg", currencySign: "SAR", dialCode: "+966"),
  Country(name: "Solomon Islands", code: "SB", flag: "assets/flags/sb.svg", currencySign: "SBD", dialCode: "+677"),
  Country(name: "Seychelles", code: "SC", flag: "assets/flags/sc.svg", currencySign: "SCR", dialCode: "+248"),
  Country(name: "Sudan", code: "SD", flag: "assets/flags/sd.svg", currencySign: "SDG", dialCode: "+249"),
  Country(name: "Sweden", code: "SE", flag: "assets/flags/se.svg", currencySign: "SEK", dialCode: "+46"),
  Country(name: "Singapore", code: "SG", flag: "assets/flags/sg.svg", currencySign: "SGD", dialCode: "+65"),
  Country(name: "Saint Helena, Ascension and Tristan da Cunha", code: "SH", flag: "assets/flags/sh.svg", currencySign: "SHP", dialCode: "+290"),
  Country(name: "Slovenia", code: "SI", flag: "assets/flags/si.svg", currencySign: "EUR", dialCode: "+386"),
  Country(name: "Svalbard and Jan Mayen Islands", code: "SJ", flag: "assets/flags/sj.svg", currencySign: "NOK", dialCode: "+47"),
  Country(name: "Slovakia", code: "SK", flag: "assets/flags/sk.svg", currencySign: "EUR", dialCode: "+421"),
  Country(name: "Sierra Leone", code: "SL", flag: "assets/flags/sl.svg", currencySign: "SLL", dialCode: "+232"),
  Country(name: "San Marino", code: "SM", flag: "assets/flags/sm.svg", currencySign: "EUR", dialCode: "+378"),
  Country(name: "Senegal", code: "SN", flag: "assets/flags/sn.svg", currencySign: "XOF", dialCode: "+221"),
  Country(name: "Somalia", code: "SO", flag: "assets/flags/so.svg", currencySign: "SOS", dialCode: "+252"),
  Country(name: "Suriname", code: "SR", flag: "assets/flags/sr.svg", currencySign: "SRD", dialCode: "+597"),
  Country(name: "South Sudan", code: "SS", flag: "assets/flags/ss.svg", currencySign: "SSP", dialCode: "+211"),
  Country(name: "Sao Tome and Principe", code: "ST", flag: "assets/flags/st.svg", currencySign: "STD", dialCode: "+239"),
  Country(name: "El Salvador", code: "SV", flag: "assets/flags/sv.svg", currencySign: "SVC", dialCode: "+503"),
  Country(name: "Sint Maarten (Dutch part)", code: "SX", flag: "assets/flags/sx.svg", currencySign: "", dialCode: "+1-721"),
  Country(name: "Syrian Arab Republic", code: "SY", flag: "assets/flags/sy.svg", currencySign: "SYP", dialCode: "+963"),
  Country(name: "Kingdom of Eswatini", code: "SZ", flag: "assets/flags/sz.svg", currencySign: "SZL", dialCode: "+268"),
  Country(name: "Turks and Caicos Islands", code: "TC", flag: "assets/flags/tc.svg", currencySign: "USD", dialCode: "+1-649"),
  Country(name: "Chad", code: "TD", flag: "assets/flags/td.svg", currencySign: "XAF", dialCode: "+235"),
  Country(name: "French Southern Territories", code: "TF", flag: "assets/flags/tf.svg", currencySign: "EUR", dialCode: "+262"),
  Country(name: "Togo", code: "TG", flag: "assets/flags/tg.svg", currencySign: "XOF", dialCode: "+228"),
  Country(name: "Thailand", code: "TH", flag: "assets/flags/th.svg", currencySign: "THB", dialCode: "+66"),
  Country(name: "Tajikistan", code: "TJ", flag: "assets/flags/tj.svg", currencySign: "TJS", dialCode: "+992"),
  Country(name: "Tokelau", code: "TK", flag: "assets/flags/tk.svg", currencySign: "NZD", dialCode: "+690"),
  Country(name: "Timor-Leste", code: "TL", flag: "assets/flags/tl.svg", currencySign: "USD", dialCode: "+670"),
  Country(name: "Turkmenistan", code: "TM", flag: "assets/flags/tm.svg", currencySign: "TMT", dialCode: "+993"),
  Country(name: "Tunisia", code: "TN", flag: "assets/flags/tn.svg", currencySign: "TND", dialCode: "+216"),
  Country(name: "Tonga", code: "TO", flag: "assets/flags/to.svg", currencySign: "TOP", dialCode: "+676"),
  Country(name: "Republic of Türkiye", code: "TR", flag: "assets/flags/tr.svg", currencySign: "TRY", dialCode: "+90"),
  Country(name: "Trinidad and Tobago", code: "TT", flag: "assets/flags/tt.svg", currencySign: "TTD", dialCode: "+1-868"),
  Country(name: "Tuvalu", code: "TV", flag: "assets/flags/tv.svg", currencySign: "AUD", dialCode: "+688"),
  Country(name: "Taiwan (Republic of China)", code: "TW", flag: "assets/flags/tw.svg", currencySign: "", dialCode: "+886"),
  Country(name: "Tanzania, United Republic of", code: "TZ", flag: "assets/flags/tz.svg", currencySign: "TZS", dialCode: "+255"),
  Country(name: "Ukraine", code: "UA", flag: "assets/flags/ua.svg", currencySign: "UAH", dialCode: "+380"),
  Country(name: "Uganda", code: "UG", flag: "assets/flags/ug.svg", currencySign: "UGX", dialCode: "+256"),
  Country(name: "US Minor Outlying Islands", code: "UM", flag: "assets/flags/um.svg", currencySign: "USD", dialCode: "+1"),
  Country(name: "United States", code: "US", flag: "assets/flags/us.svg", currencySign: "USD", dialCode: "+1"),
  Country(name: "Uruguay", code: "UY", flag: "assets/flags/uy.svg", currencySign: "UYU", dialCode: "+598"),
  Country(name: "Uzbekistan", code: "UZ", flag: "assets/flags/uz.svg", currencySign: "UZS", dialCode: "+998"),
  Country(name: "Holy See (Vatican City State)", code: "VA", flag: "assets/flags/va.svg", currencySign: "EUR", dialCode: "+379"),
  Country(name: "Saint Vincent and the Grenadines", code: "VC", flag: "assets/flags/vc.svg", currencySign: "XCD", dialCode: "+1-784"),
  Country(name: "Venezuela, Bolivarian Republic of", code: "VE", flag: "assets/flags/ve.svg", currencySign: "VEF", dialCode: "+58"),
  Country(name: "Virgin Islands, British", code: "VG", flag: "assets/flags/vg.svg", currencySign: "USD", dialCode: "+1-284"),
  Country(name: "Virgin Islands, U.S.", code: "VI", flag: "assets/flags/vi.svg", currencySign: "USD", dialCode: "+1-340"),
  Country(name: "Vietnam", code: "VN", flag: "assets/flags/vn.svg", currencySign: "VND", dialCode: "+84"),
  Country(name: "Vanuatu", code: "VU", flag: "assets/flags/vu.svg", currencySign: "VUV", dialCode: "+678"),
  Country(name: "Wallis and Futuna Islands", code: "WF", flag: "assets/flags/wf.svg", currencySign: "XPF", dialCode: "+681"),
  Country(name: "Samoa", code: "WS", flag: "assets/flags/ws.svg", currencySign: "WST", dialCode: "+685"),
  Country(name: "Kosovo", code: "XK", flag: "assets/flags/xk.svg", currencySign: "", dialCode: "+383"),
  Country(name: "Yemen", code: "YE", flag: "assets/flags/ye.svg", currencySign: "YER", dialCode: "+967"),
  Country(name: "Mayotte", code: "YT", flag: "assets/flags/yt.svg", currencySign: "EUR", dialCode: "+262"),
  Country(name: "South Africa", code: "ZA", flag: "assets/flags/za.svg", currencySign: "ZAR", dialCode: "+27"),
  Country(name: "Zambia", code: "ZM", flag: "assets/flags/zm.svg", currencySign: "ZMW", dialCode: "+260"),
  Country(name: "Zimbabwe", code: "ZW", flag: "assets/flags/zw.svg", currencySign: "ZWD", dialCode: "+263"),
];