import 'package:snapid/utlis/country_model.dart';

List<Country> allCountries = [
  Country(name: "Andorra", code: "AD", flag: "assets/flags/ad.svg", currencySign: "EUR"),
  Country(name: "United Arab Emirates", code: "AE", flag: "assets/flags/ae.svg", currencySign: "AED"),
  Country(name: "Afghanistan", code: "AF", flag: "assets/flags/af.svg", currencySign: "AFN"),
  Country(name: "Antigua and Barbuda", code: "AG", flag: "assets/flags/ag.svg", currencySign: "XCD"),
  Country(name: "Anguilla", code: "AI", flag: "assets/flags/ai.svg", currencySign: "XCD"),
  Country(name: "Albania", code: "AL", flag: "assets/flags/al.svg", currencySign: "ALL"),
  Country(name: "Armenia", code: "AM", flag: "assets/flags/am.svg", currencySign: "AMD"),
  Country(name: "Angola", code: "AO", flag: "assets/flags/ao.svg", currencySign: "AOA"),
  Country(name: "Antarctica", code: "AQ", flag: "assets/flags/aq.svg", currencySign: "XCD"),
  Country(name: "Argentina", code: "AR", flag: "assets/flags/ar.svg", currencySign: "ARS"),
  Country(name: "American Samoa", code: "AS", flag: "assets/flags/as.svg", currencySign: "USD"),
  Country(name: "Austria", code: "AT", flag: "assets/flags/at.svg", currencySign: "EUR"),
  Country(name: "Australia", code: "AU", flag: "assets/flags/au.svg", currencySign: "AUD"),
  Country(name: "Aruba", code: "AW", flag: "assets/flags/aw.svg", currencySign: "AWG"),
  Country(name: "\u00c5land Islands", code: "AX", flag: "assets/flags/ax.svg", currencySign: ""),
  Country(name: "Azerbaijan", code: "AZ", flag: "assets/flags/az.svg", currencySign: "AZN"),
  Country(name: "Bosnia and Herzegovina", code: "BA", flag: "assets/flags/ba.svg", currencySign: "BAM"),
  Country(name: "Barbados", code: "BB", flag: "assets/flags/bb.svg", currencySign: "BBD"),
  Country(name: "Bangladesh", code: "BD", flag: "assets/flags/bd.svg", currencySign: "BDT"),
  Country(name: "Belgium", code: "BE", flag: "assets/flags/be.svg", currencySign: "EUR"),
  Country(name: "Burkina Faso", code: "BF", flag: "assets/flags/bf.svg", currencySign: "XOF"),
  Country(name: "Bulgaria", code: "BG", flag: "assets/flags/bg.svg", currencySign: "BGN"),
  Country(name: "Bahrain", code: "BH", flag: "assets/flags/bh.svg", currencySign: "BHD"),
  Country(name: "Burundi", code: "BI", flag: "assets/flags/bi.svg", currencySign: "BIF"),
  Country(name: "Benin", code: "BJ", flag: "assets/flags/bj.svg", currencySign: "XOF"),
  Country(name: "Saint Barthélemy", code: "BL", flag: "assets/flags/bl.svg", currencySign: ""),
  Country(name: "Bermuda", code: "BM", flag: "assets/flags/bm.svg", currencySign: "BMD"),
  Country(name: "Brunei Darussalam", code: "BN", flag: "assets/flags/bn.svg", currencySign: "BND"),
  Country(name: "Bolivia, Plurinational State of", code: "BO", flag: "assets/flags/bo.svg", currencySign: "BOB"),
  Country(name: "Caribbean Netherlands", code: "BQ", flag: "assets/flags/bq.svg", currencySign: ""),
  Country(name: "Brazil", code: "BR", flag: "assets/flags/br.svg", currencySign: "BRL"),
  Country(name: "Bahamas", code: "BS", flag: "assets/flags/bs.svg", currencySign: "BSD"),
  Country(name: "Bhutan", code: "BT", flag: "assets/flags/bt.svg", currencySign: "BTN"),
  Country(name: "Bouvet Island", code: "BV", flag: "assets/flags/bv.svg", currencySign: "NOK"),
  Country(name: "Botswana", code: "BW", flag: "assets/flags/bw.svg", currencySign: "BWP"),
  Country(name: "Belarus", code: "BY", flag: "assets/flags/by.svg", currencySign: "BYR"),
  Country(name: "Belize", code: "BZ", flag: "assets/flags/bz.svg", currencySign: "BZD"),
  Country(name: "Canada", code: "CA", flag: "assets/flags/ca.svg", currencySign: "CAD"),
  Country(name: "Cocos (Keeling) Islands", code: "CC", flag: "assets/flags/cc.svg", currencySign: "AUD"),
  Country(name: "Congo, the Democratic Republic of the", code: "CD", flag: "assets/flags/cd.svg", currencySign: "CDF"),
  Country(name: "Central African Republic", code: "CF", flag: "assets/flags/cf.svg", currencySign: "XAF"),
  Country(name: "Republic of the Congo", code: "CG", flag: "assets/flags/cg.svg", currencySign: "XAF"),
  Country(name: "Switzerland", code: "CH", flag: "assets/flags/ch.svg", currencySign: "CHF"),
  Country(name: "C\u00f4te d'Ivoire", code: "CI", flag: "assets/flags/ci.svg", currencySign: "XOF"),
  Country(name: "Cook Islands", code: "CK", flag: "assets/flags/ck.svg", currencySign: "NZD"),
  Country(name: "Chile", code: "CL", flag: "assets/flags/cl.svg", currencySign: "CLP"),
  Country(name: "Cameroon", code: "CM", flag: "assets/flags/cm.svg", currencySign: "XAF"),
  Country(name: "China (People's Republic of China)", code: "CN", flag: "assets/flags/cn.svg", currencySign: "CNY"),
  Country(name: "Colombia", code: "CO", flag: "assets/flags/co.svg", currencySign: "COP"),
  Country(name: "Costa Rica", code: "CR", flag: "assets/flags/cr.svg", currencySign: "CRC"),
  Country(name: "Cuba", code: "CU", flag: "assets/flags/cu.svg", currencySign: "CUP"),
  Country(name: "Cape Verde", code: "CV", flag: "assets/flags/cv.svg", currencySign: "CVE"),
  Country(name: "Cura\u00e7ao", code: "CW", flag: "assets/flags/cw.svg", currencySign: ""),
  Country(name: "Christmas Island", code: "CX", flag: "assets/flags/cx.svg", currencySign: "AUD"),
  Country(name: "Cyprus", code: "CY", flag: "assets/flags/cy.svg", currencySign: "EUR"),
  Country(name: "Czech Republic", code: "CZ", flag: "assets/flags/cz.svg", currencySign: "CZK"),
  Country(name: "Germany", code: "DE", flag: "assets/flags/de.svg", currencySign: "EUR"),
  Country(name: "Djibouti", code: "DJ", flag: "assets/flags/dj.svg", currencySign: "DJF"),
  Country(name: "Denmark", code: "DK", flag: "assets/flags/dk.svg", currencySign: "DKK"),
  Country(name: "Dominica", code: "DM", flag: "assets/flags/dm.svg", currencySign: "XCD"),
  Country(name: "Dominican Republic", code: "DO", flag: "assets/flags/do.svg", currencySign: "DOP"),
  Country(name: "Algeria", code: "DZ", flag: "assets/flags/dz.svg", currencySign: "DZD"),
  Country(name: "Ecuador", code: "EC", flag: "assets/flags/ec.svg", currencySign: "ECS"),
  Country(name: "Estonia", code: "EE", flag: "assets/flags/ee.svg", currencySign: "EUR"),
  Country(name: "Egypt", code: "EG", flag: "assets/flags/eg.svg", currencySign: "EGP"),
  Country(name: "Western Sahara", code: "EH", flag: "assets/flags/eh.svg", currencySign: "MAD"),
  Country(name: "Eritrea", code: "ER", flag: "assets/flags/er.svg", currencySign: "ERN"),
  Country(name: "Spain", code: "ES", flag: "assets/flags/es.svg", currencySign: "EUR"),
  Country(name: "Ethiopia", code: "ET", flag: "assets/flags/et.svg", currencySign: "ETB"),
  Country(name: "Europe", code: "EU", flag: "assets/flags/eu.svg", currencySign: ""),
  Country(name: "Finland", code: "FI", flag: "assets/flags/fi.svg", currencySign: "EUR"),
  Country(name: "Fiji", code: "FJ", flag: "assets/flags/fj.svg", currencySign: "FJD"),
  Country(name: "Falkland Islands (Malvinas)", code: "FK", flag: "assets/flags/fk.svg", currencySign: "FKP"),
  Country(name: "Micronesia, Federated States of", code: "FM", flag: "assets/flags/fm.svg", currencySign: "USD"),
  Country(name: "Faroe Islands", code: "FO", flag: "assets/flags/fo.svg", currencySign: "DKK"),
  Country(name: "France", code: "FR", flag: "assets/flags/fr.svg", currencySign: "EUR"),
  Country(name: "Gabon", code: "GA", flag: "assets/flags/ga.svg", currencySign: "XAF"),
  Country(name: "England", code: "GB-ENG", flag: "assets/flags/gb-eng.svg", currencySign: "GBP"),
  Country(name: "Northern Ireland", code: "GB-NIR", flag: "assets/flags/gb-nir.svg", currencySign: "GBP"),
  Country(name: "Scotland", code: "GB-SCT", flag: "assets/flags/gb-sct.svg", currencySign: "GBP"),
  Country(name: "Wales", code: "GB-WLS", flag: "assets/flags/gb-wls.svg", currencySign: "GBP"),
  Country(name: "United Kingdom", code: "GB", flag: "assets/flags/gb.svg", currencySign: "GBP"),
  Country(name: "Grenada", code: "GD", flag: "assets/flags/gd.svg", currencySign: "XCD"),
  Country(name: "Georgia", code: "GE", flag: "assets/flags/ge.svg", currencySign: "GEL"),
  Country(name: "French Guiana", code: "GF", flag: "assets/flags/gf.svg", currencySign: "EUR"),
  Country(name: "Guernsey", code: "GG", flag: "assets/flags/gg.svg", currencySign: ""),
  Country(name: "Ghana", code: "GH", flag: "assets/flags/gh.svg", currencySign: "GHS"),
  Country(name: "Gibraltar", code: "GI", flag: "assets/flags/gi.svg", currencySign: "GIP"),
  Country(name: "Greenland", code: "GL", flag: "assets/flags/gl.svg", currencySign: "DKK"),
  Country(name: "Gambia", code: "GM", flag: "assets/flags/gm.svg", currencySign: "GMD"),
  Country(name: "Guinea", code: "GN", flag: "assets/flags/gn.svg", currencySign: "GNF"),
  Country(name: "Guadeloupe", code: "GP", flag: "assets/flags/gp.svg", currencySign: "EUR"),
  Country(name: "Equatorial Guinea", code: "GQ", flag: "assets/flags/gq.svg", currencySign: "XAF"),
  Country(name: "Greece", code: "GR", flag: "assets/flags/gr.svg", currencySign: "EUR"),
  Country(name: "South Georgia and the South Sandwich Islands", code: "GS", flag: "assets/flags/gs.svg", currencySign: "GBP"),
  Country(name: "Guatemala", code: "GT", flag: "assets/flags/gt.svg", currencySign: "QTQ"),
  Country(name: "Guam", code: "GU", flag: "assets/flags/gu.svg", currencySign: "USD"),
  Country(name: "Guinea-Bissau", code: "GW", flag: "assets/flags/gw.svg", currencySign: "CFA"),
  Country(name: "Guyana", code: "GY", flag: "assets/flags/gy.svg", currencySign: "GYD"),
  Country(name: "Hong Kong", code: "HK", flag: "assets/flags/hk.svg", currencySign: "HKD"),
  Country(name: "Heard Island and McDonald Islands", code: "HM", flag: "assets/flags/hm.svg", currencySign: "AUD"),
  Country(name: "Honduras", code: "HN", flag: "assets/flags/hn.svg", currencySign: "HNL"),
  Country(name: "Croatia", code: "HR", flag: "assets/flags/hr.svg", currencySign: "EUR"),
  Country(name: "Haiti", code: "HT", flag: "assets/flags/ht.svg", currencySign: "HTG"),
  Country(name: "Hungary", code: "HU", flag: "assets/flags/hu.svg", currencySign: "HUF"),
  Country(name: "Indonesia", code: "ID", flag: "assets/flags/id.svg", currencySign: "IDR"),
  Country(name: "Ireland", code: "IE", flag: "assets/flags/ie.svg", currencySign: "EUR"),
  Country(name: "Israel", code: "IL", flag: "assets/flags/il.svg", currencySign: "ILS"),
  Country(name: "Isle of Man", code: "IM", flag: "assets/flags/im.svg", currencySign: ""),
  Country(name: "India", code: "IN", flag: "assets/flags/in.svg", currencySign: "INR"),
  Country(name: "British Indian Ocean Territory", code: "IO", flag: "assets/flags/io.svg", currencySign: "USD"),
  Country(name: "Iraq", code: "IQ", flag: "assets/flags/iq.svg", currencySign: "IQD"),
  Country(name: "Iran, Islamic Republic of", code: "IR", flag: "assets/flags/ir.svg", currencySign: "IRR"),
  Country(name: "Iceland", code: "IS", flag: "assets/flags/is.svg", currencySign: "ISK"),
  Country(name: "Italy", code: "IT", flag: "assets/flags/it.svg", currencySign: "EUR"),
  Country(name: "Jersey", code: "JE", flag: "assets/flags/je.svg", currencySign: ""),
  Country(name: "Jamaica", code: "JM", flag: "assets/flags/jm.svg", currencySign: "JMD"),
  Country(name: "Jordan", code: "JO", flag: "assets/flags/jo.svg", currencySign: "JOD"),
  Country(name: "Japan", code: "JP", flag: "assets/flags/jp.svg", currencySign: "JPY"),
  Country(name: "Kenya", code: "KE", flag: "assets/flags/ke.svg", currencySign: "KES"),
  Country(name: "Kyrgyzstan", code: "KG", flag: "assets/flags/kg.svg", currencySign: "KGS"),
  Country(name: "Cambodia", code: "KH", flag: "assets/flags/kh.svg", currencySign: "KHR"),
  Country(name: "Kiribati", code: "KI", flag: "assets/flags/ki.svg", currencySign: "AUD"),
  Country(name: "Comoros", code: "KM", flag: "assets/flags/km.svg", currencySign: "KMF"),
  Country(name: "Saint Kitts and Nevis", code: "KN", flag: "assets/flags/kn.svg", currencySign: "XCD"),
  Country(name: "Korea, Democratic People's Republic of", code: "KP", flag: "assets/flags/kp.svg", currencySign: "KPW"),
  Country(name: "Korea, Republic of", code: "KR", flag: "assets/flags/kr.svg", currencySign: "KRW"),
  Country(name: "Kuwait", code: "KW", flag: "assets/flags/kw.svg", currencySign: "KWD"),
  Country(name: "Cayman Islands", code: "KY", flag: "assets/flags/ky.svg", currencySign: "KYD"),
  Country(name: "Kazakhstan", code: "KZ", flag: "assets/flags/kz.svg", currencySign: "KZT"),
  Country(name: "Laos (Lao People's Democratic Republic)", code: "LA", flag: "assets/flags/la.svg", currencySign: "LAK"),
  Country(name: "Lebanon", code: "LB", flag: "assets/flags/lb.svg", currencySign: "LBP"),
  Country(name: "Saint Lucia", code: "LC", flag: "assets/flags/lc.svg", currencySign: "XCD"),
  Country(name: "Liechtenstein", code: "LI", flag: "assets/flags/li.svg", currencySign: "CHF"),
  Country(name: "Sri Lanka", code: "LK", flag: "assets/flags/lk.svg", currencySign: "LKR"),
  Country(name: "Liberia", code: "LR", flag: "assets/flags/lr.svg", currencySign: "LRD"),
  Country(name: "Lesotho", code: "LS", flag: "assets/flags/ls.svg", currencySign: "LSL"),
  Country(name: "Lithuania", code: "LT", flag: "assets/flags/lt.svg", currencySign: "EUR"),
  Country(name: "Luxembourg", code: "LU", flag: "assets/flags/lu.svg", currencySign: "EUR"),
  Country(name: "Latvia", code: "LV", flag: "assets/flags/lv.svg", currencySign: "EUR"),
  Country(name: "Libya", code: "LY", flag: "assets/flags/ly.svg", currencySign: "LYD"),
  Country(name: "Morocco", code: "MA", flag: "assets/flags/ma.svg", currencySign: "MAD"),
  Country(name: "Monaco", code: "MC", flag: "assets/flags/mc.svg", currencySign: "EUR"),
  Country(name: "Moldova, Republic of", code: "MD", flag: "assets/flags/md.svg", currencySign: "MDL"),
  Country(name: "Montenegro", code: "ME", flag: "assets/flags/me.svg", currencySign: ""),
  Country(name: "Saint Martin", code: "MF", flag: "assets/flags/mf.svg", currencySign: ""),
  Country(name: "Madagascar", code: "MG", flag: "assets/flags/mg.svg", currencySign: "MGF"),
  Country(name: "Marshall Islands", code: "MH", flag: "assets/flags/mh.svg", currencySign: "USD"),
  Country(name: "North Macedonia", code: "MK", flag: "assets/flags/mk.svg", currencySign: "MKD"),
  Country(name: "Mali", code: "ML", flag: "assets/flags/ml.svg", currencySign: "XOF"),
  Country(name: "Myanmar", code: "MM", flag: "assets/flags/mm.svg", currencySign: "MMR"),
  Country(name: "Mongolia", code: "MN", flag: "assets/flags/mn.svg", currencySign: "MNT"),
  Country(name: "Macao", code: "MO", flag: "assets/flags/mo.svg", currencySign: "MOP"),
  Country(name: "Northern Mariana Islands", code: "MP", flag: "assets/flags/mp.svg", currencySign: "USD"),
  Country(name: "Martinique", code: "MQ", flag: "assets/flags/mq.svg", currencySign: "EUR"),
  Country(name: "Mauritania", code: "MR", flag: "assets/flags/mr.svg", currencySign: "MRO"),
  Country(name: "Montserrat", code: "MS", flag: "assets/flags/ms.svg", currencySign: "XCD"),
  Country(name: "Malta", code: "MT", flag: "assets/flags/mt.svg", currencySign: "EUR"),
  Country(name: "Mauritius", code: "MU", flag: "assets/flags/mu.svg", currencySign: "MUR"),
  Country(name: "Maldives", code: "MV", flag: "assets/flags/mv.svg", currencySign: "MVR"),
  Country(name: "Malawi", code: "MW", flag: "assets/flags/mw.svg", currencySign: "MWK"),
  Country(name: "Mexico", code: "MX", flag: "assets/flags/mx.svg", currencySign: "MXN"),
  Country(name: "Malaysia", code: "MY", flag: "assets/flags/my.svg", currencySign: "MYR"),
  Country(name: "Mozambique", code: "MZ", flag: "assets/flags/mz.svg", currencySign: "MZN"),
  Country(name: "Namibia", code: "NA", flag: "assets/flags/na.svg", currencySign: "NAD"),
  Country(name: "New Caledonia", code: "NC", flag: "assets/flags/nc.svg", currencySign: "XPF"),
  Country(name: "Niger", code: "NE", flag: "assets/flags/ne.svg", currencySign: "XOF"),
  Country(name: "Norfolk Island", code: "NF", flag: "assets/flags/nf.svg", currencySign: "AUD"),
  Country(name: "Nigeria", code: "NG", flag: "assets/flags/ng.svg", currencySign: "NGN"),
  Country(name: "Nicaragua", code: "NI", flag: "assets/flags/ni.svg", currencySign: "NIO"),
  Country(name: "Netherlands", code: "NL", flag: "assets/flags/nl.svg", currencySign: "EUR"),
  Country(name: "Norway", code: "NO", flag: "assets/flags/no.svg", currencySign: "NOK"),
  Country(name: "Nepal", code: "NP", flag: "assets/flags/np.svg", currencySign: "NPR"),
  Country(name: "Nauru", code: "NR", flag: "assets/flags/nr.svg", currencySign: "AUD"),
  Country(name: "Niue", code: "NU", flag: "assets/flags/nu.svg", currencySign: "NZD"),
  Country(name: "New Zealand", code: "NZ", flag: "assets/flags/nz.svg", currencySign: "NZD"),
  Country(name: "Oman", code: "OM", flag: "assets/flags/om.svg", currencySign: "OMR"),
  Country(name: "Panama", code: "PA", flag: "assets/flags/pa.svg", currencySign: "PAB"),
  Country(name: "Peru", code: "PE", flag: "assets/flags/pe.svg", currencySign: "PEN"),
  Country(name: "French Polynesia", code: "PF", flag: "assets/flags/pf.svg", currencySign: "XPF"),
  Country(name: "Papua New Guinea", code: "PG", flag: "assets/flags/pg.svg", currencySign: "PGK"),
  Country(name: "Philippines", code: "PH", flag: "assets/flags/ph.svg", currencySign: "PHP"),
  Country(name: "Pakistan", code: "PK", flag: "assets/flags/pk.svg", currencySign: "PKR"),
  Country(name: "Poland", code: "PL", flag: "assets/flags/pl.svg", currencySign: "PLN"),
  Country(name: "Saint Pierre and Miquelon", code: "PM", flag: "assets/flags/pm.svg", currencySign: "EUR"),
  Country(name: "Pitcairn", code: "PN", flag: "assets/flags/pn.svg", currencySign: "NZD"),
  Country(name: "Puerto Rico", code: "PR", flag: "assets/flags/pr.svg", currencySign: "USD"),
  Country(name: "Palestine", code: "PS", flag: "assets/flags/ps.svg", currencySign: ""),
  Country(name: "Portugal", code: "PT", flag: "assets/flags/pt.svg", currencySign: "EUR"),
  Country(name: "Palau", code: "PW", flag: "assets/flags/pw.svg", currencySign: "USD"),
  Country(name: "Paraguay", code: "PY", flag: "assets/flags/py.svg", currencySign: "PYG"),
  Country(name: "Qatar", code: "QA", flag: "assets/flags/qa.svg", currencySign: "QAR"),
  Country(name: "Réunion", code: "RE", flag: "assets/flags/re.svg", currencySign: "EUR"),
  Country(name: "Romania", code: "RO", flag: "assets/flags/ro.svg", currencySign: "RON"),
  Country(name: "Serbia", code: "RS", flag: "assets/flags/rs.svg", currencySign: "RSD"),
  Country(name: "Russian Federation", code: "RU", flag: "assets/flags/ru.svg", currencySign: "RUB"),
  Country(name: "Rwanda", code: "RW", flag: "assets/flags/rw.svg", currencySign: "RWF"),
  Country(name: "Saudi Arabia", code: "SA", flag: "assets/flags/sa.svg", currencySign: "SAR"),
  Country(name: "Solomon Islands", code: "SB", flag: "assets/flags/sb.svg", currencySign: "SBD"),
  Country(name: "Seychelles", code: "SC", flag: "assets/flags/sc.svg", currencySign: "SCR"),
  Country(name: "Sudan", code: "SD", flag: "assets/flags/sd.svg", currencySign: "SDG"),
  Country(name: "Sweden", code: "SE", flag: "assets/flags/se.svg", currencySign: "SEK"),
  Country(name: "Singapore", code: "SG", flag: "assets/flags/sg.svg", currencySign: "SGD"),
  Country(name: "Saint Helena, Ascension and Tristan da Cunha", code: "SH", flag: "assets/flags/sh.svg", currencySign: "SHP"),
  Country(name: "Slovenia", code: "SI", flag: "assets/flags/si.svg", currencySign: "EUR"),
  Country(name: "Svalbard and Jan Mayen Islands", code: "SJ", flag: "assets/flags/sj.svg", currencySign: "NOK"),
  Country(name: "Slovakia", code: "SK", flag: "assets/flags/sk.svg", currencySign: "EUR"),
  Country(name: "Sierra Leone", code: "SL", flag: "assets/flags/sl.svg", currencySign: "SLL"),
  Country(name: "San Marino", code: "SM", flag: "assets/flags/sm.svg", currencySign: "EUR"),
  Country(name: "Senegal", code: "SN", flag: "assets/flags/sn.svg", currencySign: "XOF"),
  Country(name: "Somalia", code: "SO", flag: "assets/flags/so.svg", currencySign: "SOS"),
  Country(name: "Suriname", code: "SR", flag: "assets/flags/sr.svg", currencySign: "SRD"),
  Country(name: "South Sudan", code: "SS", flag: "assets/flags/ss.svg", currencySign: "SSP"),
  Country(name: "Sao Tome and Principe", code: "ST", flag: "assets/flags/st.svg", currencySign: "STD"),
  Country(name: "El Salvador", code: "SV", flag: "assets/flags/sv.svg", currencySign: "SVC"),
  Country(name: "Sint Maarten (Dutch part)", code: "SX", flag: "assets/flags/sx.svg", currencySign: ""),
  Country(name: "Syrian Arab Republic", code: "SY", flag: "assets/flags/sy.svg", currencySign: "SYP"),
  Country(name: "Kingdom of Eswatini", code: "SZ", flag: "assets/flags/sz.svg", currencySign: "SZL"),
  Country(name: "Turks and Caicos Islands", code: "TC", flag: "assets/flags/tc.svg", currencySign: "USD"),
  Country(name: "Chad", code: "TD", flag: "assets/flags/td.svg", currencySign: "XAF"),
  Country(name: "French Southern Territories", code: "TF", flag: "assets/flags/tf.svg", currencySign: "EUR"),
  Country(name: "Togo", code: "TG", flag: "assets/flags/tg.svg", currencySign: "XOF"),
  Country(name: "Thailand", code: "TH", flag: "assets/flags/th.svg", currencySign: "THB"),
  Country(name: "Tajikistan", code: "TJ", flag: "assets/flags/tj.svg", currencySign: "TJS"),
  Country(name: "Tokelau", code: "TK", flag: "assets/flags/tk.svg", currencySign: "NZD"),
  Country(name: "Timor-Leste", code: "TL", flag: "assets/flags/tl.svg", currencySign: "USD"),
  Country(name: "Turkmenistan", code: "TM", flag: "assets/flags/tm.svg", currencySign: "TMT"),
  Country(name: "Tunisia", code: "TN", flag: "assets/flags/tn.svg", currencySign: "TND"),
  Country(name: "Tonga", code: "TO", flag: "assets/flags/to.svg", currencySign: "TOP"),
  Country(name: "Republic of Türkiye", code: "TR", flag: "assets/flags/tr.svg", currencySign: "TRY"),
  Country(name: "Trinidad and Tobago", code: "TT", flag: "assets/flags/tt.svg", currencySign: "TTD"),
  Country(name: "Tuvalu", code: "TV", flag: "assets/flags/tv.svg", currencySign: "AUD"),
  Country(name: "Taiwan (Republic of China)", code: "TW", flag: "assets/flags/tw.svg", currencySign: ""),
  Country(name: "Tanzania, United Republic of", code: "TZ", flag: "assets/flags/tz.svg", currencySign: "TZS"),
  Country(name: "Ukraine", code: "UA", flag: "assets/flags/ua.svg", currencySign: "UAH"),
  Country(name: "Uganda", code: "UG", flag: "assets/flags/ug.svg", currencySign: "UGX"),
  Country(name: "US Minor Outlying Islands", code: "UM", flag: "assets/flags/um.svg", currencySign: "USD"),
  Country(name: "United States", code: "US", flag: "assets/flags/us.svg", currencySign: "USD"),
  Country(name: "Uruguay", code: "UY", flag: "assets/flags/uy.svg", currencySign: "UYU"),
  Country(name: "Uzbekistan", code: "UZ", flag: "assets/flags/uz.svg", currencySign: "UZS"),
  Country(name: "Holy See (Vatican City State)", code: "VA", flag: "assets/flags/va.svg", currencySign: "EUR"),
  Country(name: "Saint Vincent and the Grenadines", code: "VC", flag: "assets/flags/vc.svg", currencySign: "XCD"),
  Country(name: "Venezuela, Bolivarian Republic of", code: "VE", flag: "assets/flags/ve.svg", currencySign: "VEF"),
  Country(name: "Virgin Islands, British", code: "VG", flag: "assets/flags/vg.svg", currencySign: "USD"),
  Country(name: "Virgin Islands, U.S.", code: "VI", flag: "assets/flags/vi.svg", currencySign: "USD"),
  Country(name: "Vietnam", code: "VN", flag: "assets/flags/vn.svg", currencySign: "VND"),
  Country(name: "Vanuatu", code: "VU", flag: "assets/flags/vu.svg", currencySign: "VUV"),
  Country(name: "Wallis and Futuna Islands", code: "WF", flag: "assets/flags/wf.svg", currencySign: "XPF"),
  Country(name: "Samoa", code: "WS", flag: "assets/flags/ws.svg", currencySign: "WST"),
  Country(name: "Kosovo", code: "XK", flag: "assets/flags/xk.svg", currencySign: ""),
  Country(name: "Yemen", code: "YE", flag: "assets/flags/ye.svg", currencySign: "YER"),
  Country(name: "Mayotte", code: "YT", flag: "assets/flags/yt.svg", currencySign: "EUR"),
  Country(name: "South Africa", code: "ZA", flag: "assets/flags/za.svg", currencySign: "ZAR"),
  Country(name: "Zambia", code: "ZM", flag: "assets/flags/zm.svg", currencySign: "ZMW"),
  Country(name: "Zimbabwe", code: "ZW", flag: "assets/flags/zw.svg", currencySign: "ZWD"),
];